### ISSUE TITLE
Releases >1.3.0 are missing the prebuild jars

### ISSUE THREAD

**Issue by cambid** [phax/en16931-cii2ubl#11]
The releases > 1.3.0 are missing the prebuild jars. Can you add those to new releases again, please?

**Comment by phax** [comment]
All the binary releases are on Maven Central and you can download the from there.
See https://repo1.maven.org/maven2/com/helger/en16931-cii2ubl/ as the start.

**Comment by phax** [comment]
Okay - point taken. Thanks. All releases were updated.
