### ISSUE TITLE
Konvertierung schlägt fehl wenn 'SellerAssignedID' leer ist, obwohl Datei eigentlich valide ist

### ISSUE THREAD

**Issue by DerHamm** [phax/en16931-cii2ubl#12]
Hallo, ich habe eine beispielhafte XRechnung von der Seite https://xr-viewer.nortal.com/: 

[homepage.txt](https://github.com/phax/en16931-cii2ubl/files/7745678/homepage.txt)

 Mit der neusten Version des Validators (https://github.com/itplr-kosit/validator-configuration-xrechnung), sowie mit der GUI-Implementation: (https://github.com/jcthiele/OpenXRechnungToolbox) kann ich die Datei prüfen und sie wird in beiden Fällen als valide ausgegeben. Wenn ich nun aber versuche diesen Converter mit der Datei zu verwenden, dann schlägt die Konvertierung fehl und die Datei wird nur bis zum Element `SellersItemIdentification` geschrieben. Hier der Stacktrace: [stacktrace.txt](https://github.com/phax/en16931-cii2ubl/files/7745691/stacktrace.txt)

Das Problem tritt nicht mehr auf, wenn ich in der Orignaldatei den Wert `SellerAssignedID` befülle, wie im Screenshot rechts:
![issue](https://user-images.githubusercontent.com/42356960/146776395-030016d0-832d-4a33-b472-dec276dc36cd.PNG)

Ist es möglich, das zu beheben? Oder kann es sein, das meine Datei doch keine valide XRechnung ist und ich den Validator falsch konfiguiert habe?

**Comment by phax** [comment]
Hallo @DerHamm,
may I please ask you to switch to English if possible.

Thanks for reporting this - will be fixed asap.

**Comment by phax** [comment]
Will be part of the 1.4.5 release

**Comment by phax** [comment]
Available on https://github.com/phax/en16931-cii2ubl/releases/tag/en16931-cii2ubl-parent-pom-1.4.5 - soon on Maven Central as well.
