### ISSUE TITLE
mapping of AppliedTradeAllowanceCharge from NetPriceProductTradePrice instead of GrossPriceProductTradePrice

### ISSUE THREAD

**Issue by cambid** [phax/en16931-cii2ubl#15]
Thanks for the very great toolset to convert CII to UBL.

I think I've found a bug in the conversation.

According to the [mapping-cii-ubl.xlsx] in the docs-folder the AppliedTradeAllowanceCharge should be fetched from the GrossPriceProductTradePrice and not from the NetPriceProductTradePrice.

I've tested with the actual HEAD and a minimal example. In the attached files.zip there are three versions of the same invoice:

1. 12119719.xml Invoice in CII-format
2. 12119719-ubl-orig.xml in UBL-format converted with the actual HEAD.
3. 12119719-ubl.xml in UBL-format after doing a minimal change in the CIIToUBL21Converter.java in Line 1337
```
aLineAgreement.getNetPriceProductTradePrice
```
```
aLineAgreement.getGrossPriceProductTradePrice
```

In the second version the allowance of 4.69 is missing completely. 

[files.zip](https://github.com/phax/en16931-cii2ubl/files/9658386/files.zip)

**Comment by phax** [comment]
@cambid Thanks for pointing that out - good catch :)
Did you find some other discrepancies as well or can build a new release?

**Comment by cambid** [comment]
@phax Thanks for the response and the quick fix in 503c373.
Should the allowance in the price in convertToCreditNote (f.e. https://github.com/phax/en16931-cii2ubl/blob/503c373532c70007d5c23c03cdbffcc5f0fd04b8/en16931-cii2ubl/src/main/java/com/helger/en16931/cii2ubl/CIIToUBL23Converter.java#L2145) be changed accordingly?

**Comment by phax** [comment]
You are so right - that happens when I work with too little focus :(
And the fieldname was also still the old one....

**Comment by cambid** [comment]
@phax Please don't worry about the missing focus. 🧉☕ for more focus. Can you please build a new release 1.4.8 or 1.4.7-1?

**Comment by phax** [comment]
Release 1.4.8 is out - enjoy and thanks
