### ISSUE TITLE
Bad convertion CalculationPercent to SpecifiedTradeAllowanceCharge

### ISSUE THREAD

**Issue by L3Mars** [phax/en16931-cii2ubl#17]
Hello Philip,

I'm using your CIIToUBL converter and it looks like there is a problem converting the CalculationPercent to MultiplierFactorNumeric. 

```java
    if (aAllowanceCharge.getCalculationPercent () != null)
    {
      // TODO calc is correct?
      aUBLAllowanceCharge.setMultiplierFactorNumeric (aAllowanceCharge.getCalculationPercentValue ().divide (CGlobal.BIGDEC_100));
    }
```

I think CalculationPercent should not be divided by 100

You can see the documentation of MultiplierFactorNumeric [here](https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-creditnote/cac-CreditNoteLine/cac-AllowanceCharge/cbc-MultiplierFactorNumeric/)

>MultiplierFactorNumeric
> Line level allowance or charge percentage
>The percentage that may be used, in conjunction with the line level allowance base amount, to calculate the line level allowance or charge amount.
>Example value: 20

PS: Thank you very much for all your work :)

**Comment by phax** [comment]
Hi @L3Mars  thanks for pointing that out.
I can confirm that the value range for `MultiplierFactorNumeric` is between 0 and 100.

**Comment by phax** [comment]
Will be part of the 1.4.9 release

**Comment by L3Mars** [comment]
@phax thank you for your promt response, it works perfectly.
