### ISSUE TITLE
TypeCode 381 should be converted to CreditNote

### ISSUE THREAD

**Issue by msccip** [phax/en16931-cii2ubl#19]
Hi,
the (Invoice)TypeCode 381 should be converted to ubl:CreditNote, not to ubl:Invoice.

**Comment by phax** [comment]
You are so true.
The target can be determined by a parameter.
* When using the Java library version, please make sure `setUBLCreationMode (EUBLCreationMode.AUTOMATIC)` is used (which is the default)
* When using the CLI version, you need to add the `--mode AUTOMATIC` parameter.

I assume you use the CLI version and I should use AUTOMATIC as the default....

**Comment by phax** [comment]
I can't remember... Will make the necessary changes for the next release.

**Comment by phax** [comment]
Is fixed in v2.0.2 that is just building.
