### ISSUE TITLE
BT-148 is missing

### ISSUE THREAD

**Issue by bdewein** [phax/en16931-cii2ubl#27]
source ([xrechnung-testsuite/src/test/technical-cases/01.01_comprehensive_test_uncefact.xml](https://github.com/itplr-kosit/xrechnung-testsuite/blob/master/src/test/technical-cases/01.01_comprehensive_test_uncefact.xml)):

![image](https://github.com/phax/en16931-cii2ubl/assets/94174875/46d11fe5-d467-4975-b1eb-0d986b4c359e)

target:

![image](https://github.com/phax/en16931-cii2ubl/assets/94174875/20ec531a-e2af-4b10-b731-0d4f887d1bac)

![image](https://github.com/phax/en16931-cii2ubl/assets/94174875/20dcc033-cb6f-45c4-b933-3584247e60fe)

**Comment by phax** [comment]
Part of the 2.2.3 release
