### ISSUE TITLE
BT-41 conversion incomplete

### ISSUE THREAD

**Issue by bdewein** [phax/en16931-cii2ubl#28]
BT-41 is not converted from CII to UBL if CII path is `/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeAgreement/ram:SellerTradeParty/ram:DefinedTradeContact/ram:DepartmentName`

![image](https://github.com/phax/en16931-cii2ubl/assets/94174875/974f5ba3-0551-4fe6-b08b-9a75e6f7bd3d)

[source](https://github.com/itplr-kosit/xrechnung-testsuite/blob/master/src/test/technical-cases/01.03_comprehensive_test_uncefact.xml):

![image](https://github.com/phax/en16931-cii2ubl/assets/94174875/3748090e-aa24-4cb4-9aaf-2635bbdfa448)

ubl:

![image](https://github.com/phax/en16931-cii2ubl/assets/94174875/ad11f81f-1640-44c0-bd5a-803d79483768)

![image](https://github.com/phax/en16931-cii2ubl/assets/94174875/a96dbfdd-bd61-45ee-a5ab-2980b92b8ce1)

**Comment by phax** [comment]
@bdewein  Thanks for pointing that out. Will be part of the next v2.2.3 release
