### ISSUE TITLE
BT-8 codes not transformed

### ISSUE THREAD

**Issue by bdewein** [phax/en16931-cii2ubl#29]
BT-8 "Value added tax point date code" is restricted to UNTDID 2005 in EN 16931-1, but there
is a restriction to UNTDID 2475 on the respective element in CII. Thus, the transformation should include a mapping of the respective codes (see chapter 4.3 in EN 16931-3-3) to prevent violation of BR-CL-06 in transformed UBL files:

| CII | UBL |
| --- | --- |
| 5 | 3 |
| 29 | 35 |
| 72 | 432 |

**Comment by phax** [comment]
Thanks. Will be part of release 2.2.3
